import type { Config } from "tailwindcss";

// Design tokens ported 1:1 from stitch_musiclounge_warm_signup_ui/DESIGN.md and
// code.html's inline tailwind.config -- the "Warm Luxury Lounge" system. Keep this
// file as the single source of truth for the theme once more Stitch screens land;
// don't let each new page redefine its own ad hoc colors.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#8f4d20",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "tertiary-fixed-dim": "#b9cbbd",
        "on-surface": "#1d1b15",
        "tertiary-fixed": "#d5e7d8",
        "on-primary-fixed": "#321200",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#5e4021",
        error: "#ba1a1a",
        "on-tertiary-container": "#f6fff5",
        "surface-dim": "#dfd9cf",
        "primary-container": "#aa6233",
        "on-secondary-container": "#7a5837",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#723609",
        "error-container": "#ffdad6",
        "surface-container": "#f3ede2",
        "on-surface-variant": "#53433b",
        "surface-container-low": "#f9f3e8",
        "surface-variant": "#e8e2d7",
        "secondary-fixed": "#ffdcbd",
        "inverse-on-surface": "#f6f0e5",
        "secondary-container": "#ffd2a8",
        "primary-fixed-dim": "#ffb68c",
        "surface-container-high": "#ede7dd",
        background: "#fff9ed",
        "secondary-fixed-dim": "#eabe95",
        outline: "#867369",
        "on-tertiary-fixed-variant": "#3a4a3f",
        primary: "#8c4a1e",
        "tertiary-container": "#68796c",
        "on-tertiary-fixed": "#101f16",
        secondary: "#795836",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1d1b15",
        "surface-bright": "#fff9ed",
        surface: "#fff9ed",
        "on-secondary-fixed": "#2c1600",
        "primary-fixed": "#ffdbc9",
        "outline-variant": "#d9c2b6",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e8e2d7",
        tertiary: "#4f6054",
        "inverse-surface": "#333029",
        "inverse-primary": "#ffb68c",
      },
      // 2xl added 2026-08-17 alongside the "sharp corners on hero photography" convention below
      // -- matches DESIGN.md's own "Large Radius: 24px ... featured containers", previously
      // defined in the abstract design doc but never actually wired into the real build config.
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        lg: "48px",
        "margin-mobile": "16px",
        md: "24px",
        "container-max": "1280px",
        sm: "12px",
        gutter: "24px",
        xs: "4px",
        xl: "80px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption-handwriting": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "caption-handwriting": ["16px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
