using MusicLounge.Domain.Common;
using MusicLounge.Domain.Enums;

namespace MusicLounge.Domain.Entities;

public class MusicShow : AuditableEntity<int>
{
    public int LoungeId { get; set; }
    public int? CategoryId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public LoungeShowFormat Format { get; set; }
    public DateTime ScheduledStart { get; set; }
    public DateTime? ScheduledEnd { get; set; }
    // Recorded when show actually starts/ends — used to calculate completion rate for settlement (D16)
    public DateTime? ActualStart { get; set; }
    public DateTime? ActualEnd { get; set; }
    public string? PosterUrl { get; set; }
    // True if poster was generated by AI — requires has_ai_poster subscription feature
    public bool PosterByAi { get; set; } = false;
    // Null = capacity follows seating_zones; set when owner wants a fixed cap
    public int? OfflineQuota { get; set; }
    // Null = unlimited online viewers
    public int? OnlineQuota { get; set; }
    public DateTime? TicketSaleClosesAt { get; set; }
    public bool CancellationAllowed { get; set; } = true;
    // Hours before show start that cancellation is still accepted
    public int? CancellationDeadlineHours { get; set; }
    // Percentage of ticket price refunded on cancellation (0–100)
    public decimal? RefundPercentage { get; set; }
    // draft / pending / published / cancelled
    public string Status { get; set; } = "draft";
    public bool IsPublic { get; set; } = true;
}
