using System.Collections.Frozen;

namespace MusicLounge.Api.Localization;

/// <summary>
/// MLACP-487. Từ điển thông điệp tiếng Việt → tiếng Anh, tra ở cửa ra duy nhất
/// (<c>GlobalExceptionHandler</c>).
///
/// <para><b>TỆP NÀY ĐƯỢC SINH BẰNG MÁY</b> từ <c>J:/MVP/ML_FE/dich-1..5.json</c> bởi
/// <c>sinh-tu-dien.mjs</c>. Sửa tay ở đây thì lần sinh sau sẽ mất. Kịch bản sinh đối chiếu từng khoá
/// với danh sách chuỗi trích thẳng từ mã nguồn và TỪ CHỐI ghi tệp nếu có khoá nào không khớp — vì
/// khoá lệch một dấu cách là bản dịch chết, mà chết IM LẶNG: hệ thống trả nguyên tiếng Việt, trông
/// hệt như "câu này chưa dịch".</para>
///
/// <para><b>VÌ SAO TRA THEO CHUỖI VIỆT CHỨ KHÔNG PHẢI THEO MÃ KHOÁ.</b> Cách "đúng sách" là đặt mã
/// cho từng thông điệp rồi sửa cả 432 chỗ gọi. Đo thật trước khi chọn: 432 chuỗi khác nhau nằm rải ở
/// <c>DomainException</c>, <c>ForbiddenException</c>, <c>ConflictException</c> và <c>WithMessage</c>
/// — nhưng <b>chỉ 19 chuỗi có nội suy biến</b>, và <b>tất cả đều chảy qua một chỗ</b>. Tra theo chuỗi
/// phủ được phần áp đảo mà KHÔNG đụng vào 432 chỗ gọi, tức không có cơ hội làm hỏng logic nghiệp vụ
/// nào — và 432 chỗ đó nằm trong luồng tiền và luồng pháp lý.</para>
///
/// <para><b>LÙI VỀ TIẾNG VIỆT, KHÔNG BAO GIỜ TRẢ RỖNG.</b> Chưa dịch thì trả nguyên câu tiếng Việt.
/// Một thông điệp tiếng Việt giữa bản tiếng Anh thì hơi lệch, nhưng một ô trống thì người dùng không
/// làm gì được với nó.</para>
///
/// <para><b>Biên dịch thẳng vào mã, không để tệp rời.</b> Ngày 23/09/2026 hệ thống mất toàn bộ
/// <c>/home</c> khi dời vùng Azure, kéo theo khoá Firebase, và mọi handler cần kho tệp trả 500. Một
/// từ điển đọc từ tệp lúc chạy sẽ thêm đúng kiểu phụ thuộc đó vào đường sinh thông điệp lỗi — thứ
/// phải sống sót được cả khi những thứ khác đã hỏng.</para>
///
/// <para>Không nằm trong từ điển này: 19 chuỗi có nội suy biến và các chuỗi mang chỗ trống của
/// FluentValidation (<c>{MaxQuantity}</c>…) — chuỗi lúc chạy khác chuỗi trong mã nên không tra chính
/// xác được. Riêng <c>NotFoundException</c> (270 chỗ gọi) được dịch bằng khuôn ở
/// <c>NotFoundException.CauTiengAnh</c>, không qua từ điển này.</para>
/// </summary>
internal static class ThongDiepSongNgu
{
    /// <summary>Trả bản tiếng Anh nếu có, không thì trả nguyên chuỗi vào.</summary>
    public static string Dich(string? viet)
        => string.IsNullOrEmpty(viet) ? viet ?? string.Empty
           : VietSangAnh.GetValueOrDefault(viet, viet);

    /// <summary>Cho test quét: mọi khoá ở đây phải còn tồn tại trong mã nguồn.</summary>
    public static IReadOnlyCollection<string> MoiKhoa => VietSangAnh.Keys;

    private static readonly FrozenDictionary<string, string> VietSangAnh =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["'From' phải trước hoặc bằng 'To'."] = "'From' must be earlier than or equal to 'To'.",
            ["AccessType phải là 'Physical' hoặc 'Livestream'."] = "AccessType must be 'Physical' or 'Livestream'.",
            ["Action không hợp lệ. Dùng 'Removed' hoặc 'Dismissed'."] = "Invalid action. Use 'Removed' or 'Dismissed'.",
            ["Action phải là 'Removed' hoặc 'Dismissed'."] = "Action must be 'Removed' or 'Dismissed'.",
            ["Ảnh phải được tải lên qua endpoint upload (POST /uploads/images) trước — không chấp nhận URL bên ngoài."] = "The image must first be uploaded through the upload endpoint (POST /uploads/images) — external URLs are not accepted.",
            ["ApprovedAmount phải lớn hơn 0."] = "ApprovedAmount must be greater than 0.",
            ["AtmosphereId không tồn tại."] = "AtmosphereId does not exist.",
            ["Bạn cần check-in (vào cửa hoặc xem livestream) để đánh giá show này."] = "You must check in (at the door or by watching the livestream) before you can rate this concert.",
            ["Bạn cần có gói subscription đang hoạt động để tạo event mới. Vui lòng đăng ký gói."] = "You need an active subscription to create a new concert. Please subscribe to a package.",
            ["Bạn cần có vé livestream để xem nội dung này."] = "You need a livestream ticket to watch this.",
            ["Bạn cần đồng ý với Điều khoản dịch vụ và Chính sách bảo mật để đăng ký."] = "You must accept the Terms of Service and the Privacy Policy to register.",
            ["Bạn chưa có gói đang hoạt động — hãy đăng ký một gói trước."] = "You have no active package — please subscribe to one first.",
            ["Bạn chưa từng đăng ký gói subscription nào — vui lòng chọn một gói để đăng ký lần đầu."] = "You have never subscribed to any package — please choose one to subscribe for the first time.",
            ["Bạn chưa từng đăng ký gói subscription nào."] = "You have never subscribed to any package.",
            ["Bạn đã báo cáo nội dung này rồi, đang chờ Admin xử lý."] = "You have already reported this content; it is awaiting review by an administrator.",
            ["Bạn đã có gói đang hoạt động — dùng Gia hạn để cộng thêm thời gian, hoặc Đổi gói để chuyển sang gói khác (phần còn lại của gói hiện tại được quy đổi sang gói mới)."] = "You already have an active package — use Renew to add more time, or Change package to move to a different one (the remainder of your current package is carried over).",
            ["Bạn đã có một phòng trà — mỗi tài khoản chủ chỉ được sở hữu một phòng trà. Hãy chỉnh sửa phòng trà hiện có thay vì tạo mới."] = "You already have a music lounge — each owner account may own only one. Please edit your existing lounge instead of creating another.",
            ["Bạn đã đánh giá show này rồi."] = "You have already rated this concert.",
            ["Bạn đã tắt tiếng phòng trà này."] = "You have already muted this music lounge.",
            ["Bạn đã theo dõi phòng trà này."] = "You already follow this music lounge.",
            ["Bạn đang có một lệnh gia hạn hoặc đổi gói chờ thanh toán — hãy hoàn tất nó, hoặc đợi nó tự huỷ nếu bỏ dở."] = "You already have a renewal or package change awaiting payment — please complete it, or wait for it to be cancelled automatically if you abandon it.",
            ["Bạn đang gửi tin nhắn quá nhanh. Vui lòng đợi vài giây rồi thử lại."] = "You are sending messages too quickly. Please wait a few seconds and try again.",
            ["Bạn không có gói subscription nào đang hoạt động để hủy."] = "You have no active subscription to cancel.",
            ["Bạn không có quyền bán vé tại quầy cho venue này."] = "You do not have permission to sell tickets at the door for this venue.",
            ["Bạn không có quyền bắt đầu show của venue này."] = "You do not have permission to start this venue's concert.",
            ["Bạn không có quyền bật/tắt chat cho livestream này."] = "You do not have permission to enable or disable chat for this livestream.",
            ["Bạn không có quyền cập nhật order F&B của venue này."] = "You do not have permission to update this venue's food and drink orders.",
            ["Bạn không có quyền check-in vé cho buổi diễn này."] = "You do not have permission to check tickets in for this concert.",
            ["Bạn không có quyền đổi hình thức event này."] = "You do not have permission to change this concert's format.",
            ["Bạn không có quyền đổi lịch event này."] = "You do not have permission to reschedule this concert.",
            ["Bạn không có quyền gắn tiêu chí cho buổi diễn này."] = "You do not have permission to attach criteria to this concert.",
            ["Bạn không có quyền giữ phiên xem này."] = "You do not have permission to hold this viewing session.",
            ["Bạn không có quyền hủy event này."] = "You do not have permission to cancel this concert.",
            ["Bạn không có quyền kết thúc livestream của venue này."] = "You do not have permission to end this venue's livestream.",
            ["Bạn không có quyền kết thúc show của venue này."] = "You do not have permission to end this venue's concert.",
            ["Bạn không có quyền nộp duyệt event này."] = "You do not have permission to submit this concert for approval.",
            ["Bạn không có quyền phát livestream của venue này."] = "You do not have permission to broadcast this venue's livestream.",
            ["Bạn không có quyền quản lý khu vực chỗ ngồi cho venue này."] = "You do not have permission to manage seating zones for this venue.",
            ["Bạn không có quyền quản lý menu cho venue này."] = "You do not have permission to manage the menu for this venue.",
            ["Bạn không có quyền quản lý staff cho venue này."] = "You do not have permission to manage staff for this venue.",
            ["Bạn không có quyền quản lý tài khoản ngân hàng của nghệ sĩ này — chỉ người tạo hồ sơ nghệ sĩ mới có quyền."] = "You do not have permission to manage this performer's bank account — only whoever created the performer profile may do so.",
            ["Bạn không có quyền quản lý tài khoản ngân hàng của venue này."] = "You do not have permission to manage this venue's bank accounts.",
            ["Bạn không có quyền sửa ảnh venue này."] = "You do not have permission to edit this venue's photos.",
            ["Bạn không có quyền sửa buổi hòa nhạc này."] = "You do not have permission to edit this concert.",
            ["Bạn không có quyền sửa danh sách biểu diễn của event này."] = "You do not have permission to edit this concert's line-up.",
            ["Bạn không có quyền sửa event này."] = "You do not have permission to edit this concert.",
            ["Bạn không có quyền sửa hạng vé này."] = "You do not have permission to edit this ticket tier.",
            ["Bạn không có quyền sửa tiêu chí của venue này."] = "You do not have permission to edit this venue's criteria.",
            ["Bạn không có quyền sửa venue này."] = "You do not have permission to edit this venue.",
            ["Bạn không có quyền tạo event cho venue này."] = "You do not have permission to create a concert for this venue.",
            ["Bạn không có quyền tạo livestream cho venue này."] = "You do not have permission to create a livestream for this venue.",
            ["Bạn không có quyền tạo order F&B cho venue này."] = "You do not have permission to create a food and drink order for this venue.",
            ["Bạn không có quyền tạo poster cho show này."] = "You do not have permission to create a poster for this concert.",
            ["Bạn không có quyền tạo tiêu chí cho venue này."] = "You do not have permission to create criteria for this venue.",
            ["Bạn không có quyền thanh toán đơn này."] = "You do not have permission to pay for this order.",
            ["Bạn không có quyền thiết lập giá vé cho event này."] = "You do not have permission to set ticket prices for this concert.",
            ["Bạn không có quyền xem ảnh CCCD/CMND này."] = "You do not have permission to view this ID card image.",
            ["Bạn không có quyền xem báo cáo doanh thu của venue này."] = "You do not have permission to view this venue's revenue report.",
            ["Bạn không có quyền xem danh sách staff của venue này."] = "You do not have permission to view this venue's staff list.",
            ["Bạn không có quyền xem dự báo của buổi diễn này."] = "You do not have permission to view this concert's forecast.",
            ["Bạn không có quyền xem đơn hàng của buổi hòa nhạc này."] = "You do not have permission to view this concert's orders.",
            ["Bạn không có quyền xem giấy phép kinh doanh của venue này."] = "You do not have permission to view this venue's business licence.",
            ["Bạn không có quyền xem lịch sử livestream của venue này."] = "You do not have permission to view this venue's livestream history.",
            ["Bạn không có quyền xem lịch sử tạo poster của show này."] = "You do not have permission to view this concert's poster generation history.",
            ["Bạn không có quyền xem order F&B của venue này."] = "You do not have permission to view this venue's food and drink orders.",
            ["Bạn không có quyền xem thống kê bán vé của buổi diễn này."] = "You do not have permission to view this concert's ticket sales statistics.",
            ["Bạn không có quyền xem thống kê của buổi diễn này."] = "You do not have permission to view this concert's statistics.",
            ["Bạn không có quyền xem thống kê của venue này."] = "You do not have permission to view this venue's statistics.",
            ["Bạn không có quyền xem thống kê donate của venue này."] = "You do not have permission to view this venue's donation statistics.",
            ["Bạn không có quyền xem thống kê vé của show này."] = "You do not have permission to view this concert's ticket statistics.",
            ["Bạn không có quyền xem thông tin phát trực tiếp của venue này."] = "You do not have permission to view this venue's broadcasting details.",
            ["Bạn không có quyền xem tiêu chí của buổi diễn này."] = "You do not have permission to view this concert's criteria.",
            ["Bạn không có quyền xem tiêu chí của venue này."] = "You do not have permission to view this venue's criteria.",
            ["Bạn không có quyền xem vé này."] = "You do not have permission to view this ticket.",
            ["Bạn không có quyền xem venue này."] = "You do not have permission to view this venue.",
            ["Bạn không có quyền xóa event này."] = "You do not have permission to delete this concert.",
            ["Bạn không có quyền xóa hạng vé này."] = "You do not have permission to delete this ticket tier.",
            ["Bạn không có quyền xóa venue này."] = "You do not have permission to delete this venue.",
            ["Bạn không có quyền xuất báo cáo doanh thu của venue này."] = "You do not have permission to export this venue's revenue report.",
            ["Bạn không còn là nhân viên của venue này."] = "You are no longer a member of staff at this venue.",
            ["Bạn không liên quan đến yêu cầu chuyển nhượng vé này."] = "You are not a party to this ticket transfer request.",
            ["Bạn không phải là người được mời nhận vé này."] = "You are not the person invited to receive this ticket.",
            ["Bạn không phải nhân viên hay chủ của phòng trà này."] = "You are neither staff nor the owner of this music lounge.",
            ["BillingCycle phải là 'Monthly', 'Quarterly' hoặc 'Yearly'."] = "BillingCycle must be 'Monthly', 'Quarterly' or 'Yearly'.",
            ["Bình luận không vượt quá 1000 ký tự."] = "The comment must not exceed 1000 characters.",
            ["Buổi diễn đã đăng chỉ được thêm hạng vé livestream, và chỉ khi hình thức là online hoặc hybrid — hạng vé vào cửa và giá đã công bố được giữ nguyên như đã hứa với người mua."] = "A published concert may only have livestream ticket tiers added, and only when its format is online or hybrid — door tiers and published prices stay exactly as promised to buyers.",
            ["Buổi diễn đã kết thúc hoặc đã bị huỷ — không còn gì để mở bán."] = "The concert has ended or been cancelled — there is nothing left to put on sale.",
            ["Buổi diễn này không có khán giả tại chỗ (chỉ diễn online hoặc đã bị huỷ) — không nhận order F&B gắn với buổi diễn này."] = "This concert has no audience on site (it is online only, or it was cancelled) — food and drink orders cannot be attached to it.",
            ["Buổi hòa nhạc này đang có một poster được tạo. Vui lòng đợi kết quả trước khi tạo thêm."] = "A poster is already being generated for this concert. Please wait for it to finish before starting another.",
            ["Category không hợp lệ."] = "Invalid category.",
            ["CategoryId không tồn tại."] = "CategoryId does not exist.",
            ["Cần bạn đồng ý cho MusicLounge xử lý email và thông tin tài khoản nhận tiền của bạn (Luật Bảo vệ dữ liệu cá nhân) trước khi xác nhận hoặc báo sai."] = "You must consent to MusicLounge processing your email address and payout account details (Personal Data Protection Law) before you can confirm or dispute.",
            ["Cần chọn ResolvedAction khi đánh dấu Resolved."] = "ResolvedAction is required when marking a complaint as Resolved.",
            ["Cần ít nhất 2 ảnh để ghép panorama."] = "At least 2 photos are needed to stitch a panorama.",
            ["Cần khai báo đã thanh toán tác quyền VCPMC trước khi bắt đầu show."] = "You must declare that VCPMC royalties have been paid before starting the concert.",
            ["Cần số tài khoản nhận hoàn."] = "The account number for the refund is required.",
            ["Cần tên chủ tài khoản."] = "The account holder's name is required.",
            ["Cần tên ngân hàng nhận hoàn."] = "The name of the bank receiving the refund is required.",
            ["Cần thiết lập livestream cho buổi diễn trước khi thêm hạng vé livestream."] = "You must set up the livestream for this concert before adding a livestream ticket tier.",
            ["Cần xác nhận đồng ý nhận hoàn bằng chuyển khoản vào tài khoản này."] = "You must confirm that you agree to be refunded by bank transfer to this account.",
            ["Chat chỉ khả dụng khi livestream đang phát sóng."] = "Chat is only available while the livestream is on air.",
            ["Chat đã bị tắt cho livestream này."] = "Chat has been disabled for this livestream.",
            ["Chỉ buổi hòa nhạc Online hoặc Hybrid mới phát được dạng 3D."] = "Only Online or Hybrid concerts can be broadcast in 3D.",
            ["Chỉ chủ phòng trà, nhân viên của phòng trà này hoặc Admin mới gỡ được lời nhắn."] = "Only the lounge owner, this lounge's staff or an administrator can remove a message.",
            ["Chỉ có thể bán vé vật lý tại quầy."] = "Only physical tickets can be sold at the door.",
            ["Chỉ có thể bắt đầu show đang ở trạng thái Published."] = "Only a concert in the Published state can be started.",
            ["Chỉ có thể check-in khi buổi diễn đang diễn ra."] = "Tickets can only be checked in while the concert is running.",
            ["Chỉ có thể chuyển nhượng vé đã xác nhận."] = "Only confirmed tickets can be transferred.",
            ["Chỉ có thể donate khi show đang diễn ra."] = "Donations are only accepted while the concert is running.",
            ["Chỉ có thể duyệt event đang chờ duyệt (Pending)."] = "Only a concert awaiting review (Pending) can be approved.",
            ["Chỉ có thể đánh giá show sau khi kết thúc."] = "A concert can only be rated after it has ended.",
            ["Chỉ có thể đổi hình thức event đã Published hoặc đang diễn ra."] = "Only a Published or running concert can have its format changed.",
            ["Chỉ có thể đổi lịch event đã Published (chưa bắt đầu diễn ra)."] = "Only a Published concert that has not yet started can be rescheduled.",
            ["Chỉ có thể gỡ livestream đang phát sóng (status = Live). Nếu đã kết thúc, chọn Dismissed."] = "Only a livestream that is on air (status = Live) can be taken down. If it has ended, choose Dismissed.",
            ["Chỉ có thể hủy vé đã xác nhận hoặc đang chờ thanh toán."] = "Only confirmed tickets or tickets awaiting payment can be cancelled.",
            ["Chỉ có thể kết thúc show đang diễn ra (Ongoing)."] = "Only a running concert (Ongoing) can be ended.",
            ["Chỉ có thể khai báo văn bản chấp thuận khi event còn ở trạng thái Draft."] = "The performance approval document can only be declared while the concert is still a Draft.",
            ["Chỉ có thể kháng cáo phạt đang ở trạng thái Active."] = "Only an Active penalty can be appealed.",
            ["Chỉ có thể khiếu nại donate chưa được trả sau khi đã quá hạn giữ tiền quy định."] = "An unpaid donation can only be disputed after the prescribed holding period has passed.",
            ["Chỉ có thể nộp duyệt event đang ở trạng thái Draft."] = "Only a concert in the Draft state can be submitted for approval.",
            ["Chỉ có thể sửa danh sách biểu diễn khi event còn ở trạng thái Draft."] = "The line-up can only be edited while the concert is still a Draft.",
            ["Chỉ có thể sửa event khi còn ở trạng thái Draft."] = "A concert can only be edited while it is still a Draft.",
            ["Chỉ có thể sửa hạng vé khi event còn ở trạng thái Draft."] = "Ticket tiers can only be edited while the concert is still a Draft.",
            ["Chỉ có thể terminate livestream đang phát sóng (status = Live)."] = "Only a livestream that is on air (status = Live) can be terminated.",
            ["Chỉ có thể thêm hạng vé khi event còn ở trạng thái Draft."] = "Ticket tiers can only be added while the concert is still a Draft.",
            ["Chỉ có thể xóa event khi còn ở trạng thái Draft."] = "A concert can only be deleted while it is still a Draft.",
            ["Chỉ có thể xóa hạng vé khi event còn ở trạng thái Draft."] = "Ticket tiers can only be deleted while the concert is still a Draft.",
            ["Chỉ có thể xử lý kháng cáo đang ở trạng thái Appealed."] = "Only an appeal in the Appealed state can be processed.",
            ["Chỉ ghi nhận chuyển khoản thủ công khi duyệt (Approved) yêu cầu hoàn tiền."] = "A manual bank transfer can only be recorded when a refund request is Approved.",
            ["Chỉ hỗ trợ đổi hình thức từ Offline sang Online sau khi đã bán vé."] = "Once tickets have been sold, only a change from Offline to Online is supported.",
            ["Chỉ người tạo hồ sơ nghệ sĩ này hoặc Admin mới có quyền sửa."] = "Only whoever created this performer profile, or an administrator, may edit it.",
            ["Chỉ Owner của venue này mới có thể kháng cáo."] = "Only this venue's owner can lodge an appeal.",
            ["Chỉ Owner của venue này mới có thể xác nhận donation."] = "Only this venue's owner can confirm a donation.",
            ["Chỉ Owner của venue này mới có thể xác nhận thanh toán cho nghệ sĩ."] = "Only this venue's owner can confirm payment to the performer.",
            ["Chỉ xác nhận trả tiền mặt cho vé bán tại quầy. Vé mua online được hoàn qua cổng thanh toán, phòng trà không cần làm gì."] = "Cash repayment is only confirmed for tickets sold at the door. Tickets bought online are refunded through the payment gateway; the lounge need do nothing.",
            ["Chủ phòng trà chưa được duyệt CCCD/CMND — cần duyệt danh tính trước để đối chiếu tên chủ tài khoản."] = "The lounge owner's ID card has not been approved — identity must be verified first so the account holder's name can be checked against it.",
            ["Chưa duyệt được hồ sơ doanh nghiệp: CCCD/CMND của người đại diện (chủ tài khoản) chưa được duyệt."] = "The business profile cannot be approved: the representative's (account holder's) ID card has not been approved.",
            ["Chưa duyệt được hồ sơ doanh nghiệp: người nộp chưa khai tên doanh nghiệp — cần khai lại hồ sơ thuế."] = "The business profile cannot be approved: the applicant has not declared the business name — the tax profile must be submitted again.",
            ["Chưa duyệt được hồ sơ doanh nghiệp: phòng trà chưa nộp giấy chứng nhận đăng ký kinh doanh để đối chiếu."] = "The business profile cannot be approved: the lounge has not submitted its business registration certificate for comparison.",
            ["Danh sách ảnh không khớp với ảnh hiện có của phòng trà này."] = "The list of photos does not match the photos this lounge currently has.",
            ["Danh sách thứ tự ảnh có Id trùng lặp."] = "The photo ordering list contains duplicate ids.",
            ["Danh sách thứ tự ảnh không được để trống."] = "The photo ordering list must not be empty.",
            ["Decision phải là 'Approved' hoặc 'Rejected'."] = "Decision must be 'Approved' or 'Rejected'.",
            ["Decision phải là 'Release' hoặc 'Withhold'."] = "Decision must be 'Release' or 'Withhold'.",
            ["Decision phải là Confirm hoặc Dispute."] = "Decision must be Confirm or Dispute.",
            ["Doanh nghiệp phải khai tên doanh nghiệp đúng như trên giấy chứng nhận đăng ký kinh doanh."] = "The business name must be declared exactly as it appears on the business registration certificate.",
            ["Donate này không có lời nhắn nào để gỡ."] = "This donation has no message to remove.",
            ["Donation đã bị huỷ (thanh toán VNPay thất bại). Không thể xác nhận."] = "This donation was cancelled (the VNPay payment failed) and cannot be confirmed.",
            ["Donation không ở trạng thái chờ xác nhận của Owner."] = "This donation is not awaiting the owner's confirmation.",
            ["DonationId không hợp lệ."] = "DonationId is not valid.",
            ["Dữ liệu đã tồn tại hoặc xung đột, vui lòng thử lại."] = "This data already exists or conflicts with existing data; please try again.",
            ["Dữ liệu gửi lên không hợp lệ."] = "The submitted data is not valid.",
            ["Dữ liệu tài khoản đã được xóa trước đó."] = "This account's data has already been erased.",
            ["Đã có lỗi hệ thống. Vui lòng thử lại sau."] = "A system error occurred. Please try again later.",
            ["Đã hết hạn đánh giá show này (7 ngày sau khi kết thúc)."] = "The window for rating this concert has closed (7 days after it ended).",
            ["Đã xác nhận trả tiền cho yêu cầu này từ trước."] = "Repayment for this request has already been confirmed.",
            ["Đánh giá này đã bị gỡ trước đó."] = "This rating has already been removed.",
            ["Đây là gói bạn đang dùng — dùng Gia hạn để cộng thêm thời gian."] = "This is the package you are already on — use Renew to add more time.",
            ["Địa chỉ IP không được rỗng."] = "The IP address must not be empty.",
            ["Điểm đánh giá phải từ 1 đến 5."] = "The rating score must be between 1 and 5.",
            ["Đối tượng bị khiếu nại (TargetType/TargetId) không tồn tại."] = "The subject of the complaint (TargetType/TargetId) does not exist.",
            ["Đơn hàng phải có ít nhất 1 món."] = "An order must contain at least 1 item.",
            ["Đơn này đã bị huỷ, không thể thanh toán."] = "This order was cancelled and cannot be paid.",
            ["Đơn này đã được thanh toán."] = "This order has already been paid.",
            ["Đơn tạo poster này không còn do máy trạm của bạn giữ (có thể đã hết hạn và được giao lại)."] = "This poster job is no longer held by your worker (it may have expired and been reassigned).",
            ["Đợt bán vé này chỉ bán online, không thể bán tại quầy."] = "This sale phase is online only and cannot be sold at the door.",
            ["Đợt bán vé này chưa mở hoặc đã kết thúc."] = "This sale phase has not opened yet, or has already closed.",
            ["Đường dẫn ảnh không hợp lệ."] = "The image path is not valid.",
            ["Email Google chưa được xác minh."] = "This Google email address has not been verified.",
            ["Email không được để trống."] = "Email must not be empty.",
            ["Email không hợp lệ."] = "Email is not valid.",
            ["Email này đã được đăng ký. Vui lòng đăng nhập hoặc dùng email khác."] = "This email address is already registered. Please sign in, or use a different address.",
            ["Event bán vé cần khai báo văn bản chấp thuận tổ chức biểu diễn (NĐ 144/2020 Điều 10) trước khi nộp duyệt."] = "A ticketed concert must declare its performance approval document (Decree 144/2020, Article 10) before it is submitted for approval.",
            ["Event đã đóng bán vé."] = "Ticket sales for this concert have closed.",
            ["Event đã kết thúc hoặc đã bị hủy trước đó."] = "This concert has already ended or been cancelled.",
            ["Event đã kết thúc hoặc đã hủy, không thể nhận chuyển nhượng vé."] = "This concert has ended or been cancelled, so no ticket transfer can be accepted.",
            ["Event này đã được duyệt trước đó."] = "This concert has already been approved.",
            ["Event này không cho phép hủy vé."] = "This concert does not allow tickets to be cancelled.",
            ["Event online hoặc có vé livestream phải được thiết lập Livestream trước khi nộp duyệt."] = "An online concert, or one with livestream tickets, must have its livestream set up before it is submitted for approval.",
            ["Event phải có ít nhất 1 hạng vé trước khi nộp duyệt."] = "A concert must have at least 1 ticket tier before it is submitted for approval.",
            ["Event phải có ít nhất 1 nghệ sĩ trong danh sách biểu diễn trước khi nộp duyệt."] = "A concert must have at least 1 performer in its line-up before it is submitted for approval.",
            ["EvidenceRef không được vượt quá 500 ký tự."] = "EvidenceRef must not exceed 500 characters.",
            ["File ảnh không được vượt quá 5MB."] = "The image file must not exceed 5MB.",
            ["File mô hình 3D không được vượt quá 30MB."] = "The 3D model file must not exceed 30MB.",
            ["Format phải là 'Offline', 'Online' hoặc 'Hybrid'."] = "Format must be 'Offline', 'Online' or 'Hybrid'.",
            ["GenreId không tồn tại."] = "GenreId does not exist.",
            ["Ghi chú duyệt không được vượt quá 1000 ký tự."] = "The review note must not exceed 1000 characters.",
            ["Ghi chú không được vượt quá 500 ký tự."] = "The note must not exceed 500 characters.",
            ["Giá cao nhất không được là số âm."] = "The maximum price must not be negative.",
            ["Giá cao nhất phải lớn hơn hoặc bằng giá thấp nhất."] = "The maximum price must be greater than or equal to the minimum price.",
            ["Giá phải là số nguyên đồng (đồng Việt Nam không có đơn vị lẻ)."] = "Prices must be whole đồng (the Vietnamese đồng has no subunit).",
            ["Giá thấp nhất không được là số âm."] = "The minimum price must not be negative.",
            ["Giá trị không được để trống."] = "The value must not be empty.",
            ["Giao dịch này còn yêu cầu hoàn tiền chưa xử lý. Xử lý hoàn tiền trước, nếu không phòng trà nhận đủ tiền cho phần sắp phải trả lại cho khách."] = "This payment still has an unresolved refund request. Settle the refund first, otherwise the lounge is paid in full for money that is about to be returned to the buyer.",
            ["Giao dịch này trả bằng tiền mặt tại quầy — không có chuyển khoản nào để ghi nhận. Hãy duyệt bình thường; phòng trà hoàn tiền mặt và xác nhận đã trả."] = "This payment was made in cash at the door — there is no bank transfer to record. Approve it as normal; the lounge refunds the cash and confirms it has done so.",
            ["Giao dịch này vẫn trong thời hạn VNPay nhận lệnh hoàn — hãy duyệt để hoàn qua VNPay, không ghi nhận chuyển khoản thủ công."] = "This payment is still inside VNPay's refund window — approve it to refund through VNPay rather than recording a manual transfer.",
            ["Gói có AI poster phải cho ít nhất 1 poster/tháng."] = "A package that includes AI posters must allow at least 1 poster per month.",
            ["Gói đã có Owner đang sử dụng — không thể sửa Giá/Số vé tối đa/AI Poster/Số scene tour. Hãy tạo gói mới và deactivate gói cũ nếu muốn thay đổi các điều khoản này."] = "This package is already in use by owners — its price, ticket cap, AI poster allowance and tour scene allowance cannot be changed. Create a new package and deactivate the old one if these terms need to change.",
            ["Gói này hiện không mở đăng ký."] = "This package is not currently open for subscription.",
            ["Gói subscription hiện tại của bạn không bao gồm tính năng tạo poster AI."] = "Your current subscription package does not include AI poster generation.",
            ["Google ID token không hợp lệ hoặc đã hết hạn."] = "The Google ID token is invalid or has expired.",
            ["Google ID token thiếu định danh người dùng."] = "The Google ID token is missing the user identifier.",
            ["Google ID token thiếu email."] = "The Google ID token is missing the email address.",
            ["Hạng vé này đã được duyệt trước đó."] = "This ticket tier has already been approved.",
            ["Hạng vé này đang chờ duyệt, chưa mở bán."] = "This ticket tier is awaiting approval and is not yet on sale.",
            ["Hành động \"Refund\" chỉ áp dụng cho khiếu nại về một show (TargetType = \"show\") — hoàn tiền vé của chính người khiếu nại, show vẫn diễn ra bình thường. Muốn hủy show và hoàn 100% cho mọi khán giả thì dùng \"TakeDownContent\". Với khiếu nại donate chưa trả nghệ sĩ, dùng \"IssueWarning\" để xử phạt venue."] = "The \"Refund\" action applies only to a complaint about a concert (TargetType = \"show\") — it refunds the complainant's own ticket while the concert goes ahead as normal. To cancel the concert and refund every attendee in full, use \"TakeDownContent\". For a complaint about a donation not paid to a performer, use \"IssueWarning\" to penalise the venue.",
            ["Họ tên không được để trống."] = "Full name must not be empty.",
            ["HoldId không hợp lệ."] = "HoldId is not valid.",
            ["Hotspot không thể trỏ về chính scene đang chứa nó."] = "A hotspot cannot point back at the scene that contains it.",
            ["Hotspot loại Navigate phải có TargetSceneId."] = "A Navigate hotspot must have a TargetSceneId.",
            ["Hồ sơ phòng trà này đã bị từ chối trước đó."] = "This lounge application has already been rejected.",
            ["IdToken không được để trống."] = "IdToken must not be empty.",
            ["Key phải là chữ thường, số, gạch dưới, bắt đầu bằng chữ (vd: performance_language)."] = "The key must consist of lower-case letters, digits and underscores, and must start with a letter (for example: performance_language).",
            ["Khiếu nại này do khách vãng lai gửi (không có tài khoản), nên không xác định được vé của ai để hoàn. Hãy liên hệ người khiếu nại theo số điện thoại đã cung cấp."] = "This complaint was filed by a guest with no account, so there is no way to tell whose ticket to refund. Please contact the complainant on the phone number they provided.",
            ["Khiếu nại này đã được xử lý xong."] = "This complaint has already been resolved.",
            ["Không đọc được kích thước ảnh. Hãy tải lên ảnh 360° dạng JPEG, PNG hoặc WebP."] = "The image dimensions could not be read. Please upload a 360° image in JPEG, PNG or WebP format.",
            ["Không thể bán vé cho show này."] = "Tickets cannot be sold for this concert.",
            ["Không thể chuyển nhượng vé cho chính mình."] = "You cannot transfer a ticket to yourself.",
            ["Không thể chuyển nhượng vé của event đã kết thúc hoặc đã hủy."] = "Tickets for a concert that has ended or been cancelled cannot be transferred.",
            ["Không thể đổi hình thức phát cho buổi hòa nhạc đã kết thúc hoặc đã hủy."] = "The broadcast format cannot be changed for a concert that has ended or been cancelled.",
            ["Không thể hủy vé sau khi event đã kết thúc."] = "A ticket cannot be cancelled once the concert has ended.",
            ["Không thể khai báo tác quyền VCPMC sau khi show đã bắt đầu/kết thúc/hủy."] = "VCPMC royalties cannot be declared once the concert has started, ended or been cancelled.",
            ["Không thể khoá Admin cuối cùng còn hoạt động."] = "The last remaining active administrator cannot be locked.",
            ["Không thể khoá tài khoản của chính bạn — bạn là Admin cuối cùng còn hoạt động."] = "You cannot lock your own account — you are the last remaining active administrator.",
            ["Không thể tải khoá xác minh Google."] = "Google's verification keys could not be downloaded.",
            ["Không thể tạo livestream cho show đã hủy hoặc đã kết thúc."] = "A livestream cannot be created for a concert that has been cancelled or has ended.",
            ["Không thể thay đổi quyết định khi livestream đã/đang phát sóng."] = "The decision cannot be changed once the livestream is on air or has aired.",
            ["Không thể tự khoá tài khoản của chính mình."] = "You cannot lock your own account.",
            ["Không thể xác định venue để xử phạt từ khiếu nại này (TargetType không liên kết được tới 1 venue cụ thể)."] = "No venue to penalise can be identified from this complaint (its TargetType does not map to one specific venue).",
            ["Không thể xử lý file này."] = "This file cannot be processed.",
            ["Không tìm thấy ảnh đã upload — vui lòng upload lại."] = "The uploaded image could not be found — please upload it again.",
            ["Không tìm thấy ảnh."] = "The image could not be found.",
            ["Không tìm thấy khoản thanh toán online của đơn này để hoàn — không thể huỷ."] = "No online payment could be found for this order to refund, so it cannot be cancelled.",
            ["Không xác định được chủ phòng trà cho giao dịch này."] = "The lounge owner for this payment could not be determined.",
            ["Không xác định được người dùng hiện tại."] = "The current user could not be determined.",
            ["Không xác định được phiên đăng nhập hiện tại."] = "The current sign-in session could not be determined.",
            ["Không xác định được vé của giao dịch này."] = "The ticket for this payment could not be determined.",
            ["Khu vực này đã vượt sức chứa thực tế."] = "This zone is already over its real capacity.",
            ["Khu vực này đã vượt sức chứa thực tế. Vui lòng chọn khu vực hoặc hạng vé khác."] = "This zone is already over its real capacity. Please choose a different zone or ticket tier.",
            ["Khu vực này không thuộc venue này."] = "This zone does not belong to this venue.",
            ["Khu vực ngồi này đã hết chỗ."] = "This seating zone is full.",
            ["Khu vực ngồi này đã hết chỗ. Vui lòng chọn khu vực hoặc hạng vé khác."] = "This seating zone is full. Please choose a different zone or ticket tier.",
            ["Liên kết đã hết hạn. Hãy liên hệ phòng trà để được gửi liên kết mới."] = "This link has expired. Please contact the lounge to have a new one sent.",
            ["Liên kết này đã được dùng — mỗi liên kết chỉ dùng được một lần."] = "This link has already been used — each link works only once.",
            ["Liên kết này không gắn với khoản donate nào."] = "This link is not attached to any donation.",
            ["Link đặt lại mật khẩu không hợp lệ hoặc đã hết hạn (link chỉ dùng được 1 lần trong thời gian giới hạn). Vui lòng yêu cầu gửi lại link mới."] = "The password reset link is invalid or has expired (each link works once, within a limited time). Please request a new one.",
            ["Livestream chưa được Admin duyệt. Không thể phát sóng."] = "This livestream has not been approved by an administrator and cannot go on air.",
            ["Livestream này đã được duyệt trước đó."] = "This livestream has already been approved.",
            ["LivestreamId không hợp lệ."] = "LivestreamId is not valid.",
            ["LoungeId không hợp lệ."] = "LoungeId is not valid.",
            ["LoungeId không tồn tại."] = "LoungeId does not exist.",
            ["LoungeShow đã có trong danh sách yêu thích."] = "This concert is already in your wishlist.",
            ["Lý do buộc dừng livestream là bắt buộc."] = "A reason is required when forcibly stopping a livestream.",
            ["Lý do kháng cáo không được vượt quá 1000 ký tự."] = "The appeal reason must not exceed 1000 characters.",
            ["Lý do không được vượt quá 1000 ký tự."] = "The reason must not exceed 1000 characters.",
            ["Lý do không được vượt quá 500 ký tự."] = "The reason must not exceed 500 characters.",
            ["Lý do không vượt quá 1000 ký tự."] = "The reason must not exceed 1000 characters.",
            ["Lý do thay đổi quá ngắn, hãy mô tả rõ vì sao cần đổi giá trị này."] = "The reason for the change is too short — please explain clearly why this value needs to change.",
            ["Mã lượt bán này đã dùng cho một lượt bán khác. Hãy tạo lượt bán mới trên máy quầy."] = "This sale reference has already been used for a different sale. Please start a new sale on the box-office device.",
            ["Mã QR không được rỗng."] = "The QR code must not be empty.",
            ["Mã số thuế không được để trống."] = "The tax code must not be empty.",
            ["Mã số thuế này đã được đăng ký bởi tài khoản khác."] = "This tax code is already registered to another account.",
            ["Mã số thuế phải gồm 10 chữ số, hoặc 10 chữ số kèm 3 chữ số đơn vị trực thuộc (ví dụ 0123456789-001)."] = "A tax code must be 10 digits, or 10 digits followed by a 3-digit branch number (for example 0123456789-001).",
            ["Mã tham chiếu thanh toán không được rỗng."] = "The payment reference must not be empty.",
            ["Mã tham chiếu thanh toán không được vượt quá 255 ký tự."] = "The payment reference must not exceed 255 characters.",
            ["Mã xác thực đã hết hạn. Vui lòng yêu cầu gửi lại mã."] = "The verification code has expired. Please request a new one.",
            ["Mã xác thực không đúng."] = "The verification code is incorrect.",
            ["Mã xác thực không được để trống."] = "The verification code must not be empty.",
            ["Mã xác thực phải gồm đúng 6 chữ số."] = "The verification code must be exactly 6 digits.",
            ["ManualTransferReference không được rỗng khi được gửi."] = "ManualTransferReference must not be empty when it is supplied.",
            ["Màu phải ở định dạng hex (#RRGGBB hoặc #RRGGBBAA)."] = "The colour must be in hex format (#RRGGBB or #RRGGBBAA).",
            ["Mật khẩu không được dài quá 64 ký tự."] = "The password must not be longer than 64 characters.",
            ["Mật khẩu không được để trống."] = "Password must not be empty.",
            ["Mật khẩu phải có ít nhất 15 ký tự. Mẹo: một cụm từ dễ nhớ thường vừa dài vừa an toàn hơn một chuỗi ký tự rối, ví dụ \"toi thich nghe nhac trinh\"."] = "The password must be at least 15 characters. Tip: a memorable phrase is usually both longer and safer than a jumble of characters — for example \"toi thich nghe nhac trinh\".",
            ["Mật khẩu xác nhận không đúng."] = "The confirmation password does not match.",
            ["MenuId không hợp lệ."] = "MenuId is not valid.",
            ["MenuId không tồn tại."] = "MenuId does not exist.",
            ["MenuItemId không hợp lệ."] = "MenuItemId is not valid.",
            ["Món này đã có trong đơn hàng — không thể xoá. Hãy ẩn món thay vì xoá."] = "This item already appears on an order and cannot be deleted. Hide it instead.",
            ["MoodId không tồn tại."] = "MoodId does not exist.",
            ["Mỗi performance phải có PerformerId hoặc PerformerName."] = "Each performance must have either a PerformerId or a PerformerName.",
            ["Ngày sinh phải là một ngày trong quá khứ."] = "The date of birth must be in the past.",
            ["Nghệ sĩ chưa đăng ký tài khoản ngân hàng mặc định — không thể xác nhận đã thanh toán cho tới khi có tài khoản để ghi nhận."] = "This performer has no default bank account on file — payment cannot be confirmed until there is an account to record it against.",
            ["Nghệ sĩ này đã có trong danh sách biểu diễn của event này."] = "This performer is already in this concert's line-up.",
            ["Nghệ sĩ này không nhận donate."] = "This performer does not accept donations.",
            ["Ngôn ngữ chỉ nhận một trong hai giá trị: vi hoặc en."] = "Language must be one of two values: vi or en.",
            ["Người dùng này chưa khai báo hồ sơ thuế nào để duyệt."] = "This user has not submitted any tax profile for review.",
            ["Người dùng này chưa nộp CCCD/CMND nào để duyệt."] = "This user has not submitted any ID card for review.",
            ["Người khiếu nại không có vé nào còn hiệu lực (và có giao dịch thanh toán) cho show này, nên không có gì để hoàn."] = "The complainant holds no valid, paid-for ticket to this concert, so there is nothing to refund.",
            ["Người mua chưa đồng ý nhận hoàn bằng chuyển khoản và chưa khai tài khoản nhận. Theo Luật Bảo vệ quyền lợi người tiêu dùng 2023 (Điều 38 khoản 4), tiền phải hoàn theo phương thức người mua đã thanh toán, trừ khi họ đồng ý phương thức khác — hệ thống đang nhắc người mua khai tài khoản."] = "The buyer has not agreed to be refunded by bank transfer and has not supplied an account. Under the Law on Protection of Consumer Rights 2023 (Article 38, clause 4), money must be refunded by the method the buyer paid with unless they agree to another — the system is prompting the buyer for their account details.",
            ["NotificationId không hợp lệ."] = "NotificationId is not valid.",
            ["Nội dung file không khớp với định dạng đã khai báo — file có thể bị đổi tên hoặc hỏng."] = "The file's contents do not match its declared format — it may have been renamed or corrupted.",
            ["Nội dung tải lên không phải là ảnh nhận dạng được."] = "The uploaded content is not a recognisable image.",
            ["Options bắt buộc với DataType Select/Range."] = "Options are required for the Select and Range data types.",
            ["Options của DataType Range có min lớn hơn max."] = "For the Range data type, the options have a minimum greater than the maximum.",
            ["Options của DataType Range phải là đối tượng JSON, vd: {\"min\":1,\"max\":5}."] = "For the Range data type, the options must be a JSON object — for example {\"min\":1,\"max\":5}.",
            ["Options của DataType Select phải là mảng JSON các chuỗi, vd: [\"Bolero\",\"Acoustic\"]."] = "For the Select data type, the options must be a JSON array of strings — for example [\"Bolero\",\"Acoustic\"].",
            ["Options phải là JSON hợp lệ."] = "Options must be valid JSON.",
            ["OrderId không hợp lệ."] = "OrderId is not valid.",
            ["Owner chỉ có thể xác nhận đã trả sau khi đã xác nhận nhận tiền."] = "The owner can only confirm payment out after confirming the money was received.",
            ["OwnerId không hợp lệ."] = "OwnerId is not valid.",
            ["PackageId không tồn tại."] = "PackageId does not exist.",
            ["PenaltyId không hợp lệ."] = "PenaltyId is not valid.",
            ["PenaltyType phải là 'Warning', 'Suspension' hoặc 'Ban'."] = "PenaltyType must be 'Warning', 'Suspension' or 'Ban'.",
            ["PerformanceId không hợp lệ."] = "PerformanceId is not valid.",
            ["PerformanceId không tồn tại."] = "PerformanceId does not exist.",
            ["Phải có ít nhất 1 đợt giá vé."] = "There must be at least 1 ticket price phase.",
            ["Phải cung cấp PerformerId hoặc PerformerName."] = "Either a PerformerId or a PerformerName must be supplied.",
            ["Phải ghi lý do cho quyết định này."] = "A reason must be given for this decision.",
            ["Phải ghi lý do kháng cáo."] = "A reason for the appeal must be given.",
            ["Phải ghi lý do khi từ chối hồ sơ phòng trà."] = "A reason must be given when rejecting a lounge application.",
            ["Phải ghi lý do khi từ chối."] = "A reason must be given when rejecting.",
            ["Phải ghi lý do phạt."] = "A reason for the penalty must be given.",
            ["Phải ghi lý do thay đổi — đây là dấu vết kiểm toán, không phải trường tuỳ chọn."] = "A reason for the change must be given — this is an audit trail, not an optional field.",
            ["Phải nêu lý do gỡ đánh giá."] = "A reason must be given for removing the rating.",
            ["Phạt này đã được kháng cáo trước đó."] = "This penalty has already been appealed.",
            ["Phạt tạm khoá cần khai số ngày tạm khoá."] = "A suspension penalty must state how many days the suspension lasts.",
            ["Phiên đăng nhập đã hết hiệu lực, vui lòng đăng nhập lại."] = "Your session has expired; please sign in again.",
            ["Phòng trà chưa đăng ký tài khoản nhận tiền — ghi bút toán chi trả bây giờ sẽ ghi có cho một khoản không lệnh chuyển khoản nào đi theo được."] = "The lounge has no payout account on file — recording a payout entry now would credit an amount that no transfer can follow.",
            ["Phòng trà đang có buổi diễn, không thể xóa."] = "This lounge has concerts scheduled and cannot be deleted.",
            ["Phòng trà này đã được duyệt trước đó."] = "This lounge has already been approved.",
            ["Platform không được vượt quá 20 ký tự."] = "Platform must not exceed 20 characters.",
            ["PriceId không hợp lệ."] = "PriceId is not valid.",
            ["PriceId không tồn tại."] = "PriceId does not exist.",
            ["PurchaseChannel phải là 'Online', 'Offline' hoặc 'Both'."] = "PurchaseChannel must be 'Online', 'Offline' or 'Both'.",
            ["Query params không được null."] = "Query parameters must not be null.",
            ["Quyết định không hợp lệ. Dùng 'Approved' hoặc 'Rejected'."] = "Invalid decision. Use 'Approved' or 'Rejected'.",
            ["Quyết định phải là 'Approved' hoặc 'Rejected'."] = "The decision must be 'Approved' or 'Rejected'.",
            ["Quyết định phải là 'Overturned' hoặc 'Upheld'."] = "The decision must be 'Overturned' or 'Upheld'.",
            ["RatingId không hợp lệ."] = "RatingId is not valid.",
            ["RawBody không được rỗng."] = "RawBody must not be empty.",
            ["Refresh token không được để trống."] = "The refresh token must not be empty.",
            ["Refresh token không hợp lệ hoặc đã hết hạn."] = "The refresh token is invalid or has expired.",
            ["ResolvedAction không hợp lệ."] = "ResolvedAction is not valid.",
            ["Role tự đăng ký chỉ có thể là 'Audience' hoặc 'Owner'."] = "Self-registration is only allowed for the 'Audience' or 'Owner' role.",
            ["Show đã hết vé vật lý."] = "This concert has sold out of physical tickets.",
            ["Show đang phát trực tiếp — hãy dừng (terminate) livestream trước khi có thể gỡ bỏ nội dung."] = "The concert is on air — terminate the livestream before the content can be taken down.",
            ["Show đang phát trực tiếp — hãy dừng (terminate) livestream trước khi hủy event."] = "The concert is on air — terminate the livestream before cancelling it.",
            ["Show đang phát trực tiếp — hãy gỡ livestream trước khi có thể gỡ bỏ event."] = "The concert is on air — take the livestream down before the concert can be removed.",
            ["Show này có livestream — dùng chức năng bắt đầu livestream thay vì lệnh này."] = "This concert has a livestream — use the start-livestream function instead of this command.",
            ["Show này có livestream — dùng chức năng kết thúc livestream thay vì lệnh này."] = "This concert has a livestream — use the end-livestream function instead of this command.",
            ["Show này không thuộc venue này."] = "This concert does not belong to this venue.",
            ["ShowId không hợp lệ."] = "ShowId is not valid.",
            ["ShowId không tồn tại."] = "ShowId does not exist.",
            ["Side phải là 'front' hoặc 'back'."] = "Side must be 'front' or 'back'.",
            ["Số CCCD/CMND không được để trống."] = "The ID card number must not be empty.",
            ["Số CCCD/CMND này đã được đăng ký bởi tài khoản khác."] = "This ID card number is already registered to another account.",
            ["Số CCCD/CMND phải gồm 9 hoặc 12 chữ số."] = "The ID card number must be 9 or 12 digits.",
            ["Số điện thoại đã được xác thực."] = "This phone number has already been verified.",
            ["Số lượng vé trong đợt bán này không đủ."] = "There are not enough tickets left in this sale phase.",
            ["Số lượng vé trong đợt bán này không đủ. Vui lòng giảm số lượng hoặc chọn đợt bán/hạng vé khác."] = "There are not enough tickets left in this sale phase. Please reduce the quantity, or choose a different phase or tier.",
            ["Số ngày tạm khoá phải lớn hơn 0."] = "The number of suspension days must be greater than 0.",
            ["Số tài khoản chỉ gồm chữ số, từ 6 đến 20 số."] = "An account number must be 6 to 20 digits, with no other characters.",
            ["Số tài khoản này không còn đọc được trên hệ thống (khoá mã hoá cũ đã mất) — chủ phòng trà cần nhập lại tài khoản trước khi xác minh."] = "This account number can no longer be read by the system (the old encryption key was lost) — the lounge owner must re-enter the account before it can be verified.",
            ["Số tiền hoàn không được vượt quá số tiền đã thanh toán."] = "The refund amount must not exceed the amount paid.",
            ["Số tiền tối thiểu là 1đ."] = "The minimum amount is 1đ.",
            ["Staff này đã bị vô hiệu hóa trước đó."] = "This staff member has already been deactivated.",
            ["Status phải là 'Pending', 'Preparing', 'Served', 'Paid' hoặc 'Cancelled'."] = "Status must be 'Pending', 'Preparing', 'Served', 'Paid' or 'Cancelled'.",
            ["Tài khoản của nghệ sĩ do chính nghệ sĩ xác nhận qua liên kết gửi email, không duyệt ở đây."] = "A performer's account is confirmed by the performer themselves through the link sent by email; it is not approved here.",
            ["Tài khoản đã bị khóa do vi phạm quy định sử dụng. Vui lòng liên hệ hỗ trợ nếu bạn cho rằng đây là nhầm lẫn."] = "This account has been locked for breaching the terms of use. Please contact support if you believe this is a mistake.",
            ["Tài khoản đã bị khóa hoặc không còn tồn tại."] = "This account has been locked, or no longer exists.",
            ["Tài khoản đã được xác thực, vui lòng đăng nhập."] = "This account has already been verified; please sign in.",
            ["Tài khoản này đang là staff đang hoạt động của venue khác. Mỗi venue cần một tài khoản staff riêng — hãy tạo tài khoản mới cho venue này."] = "This account is already active staff at another venue. Each venue needs its own staff account — please create a new account for this venue.",
            ["Tài khoản ngân hàng trong liên kết này không còn tồn tại."] = "The bank account referenced by this link no longer exists.",
            ["TakeDownContent chỉ áp dụng cho khiếu nại về show (TargetType = \"show\")."] = "TakeDownContent applies only to a complaint about a concert (TargetType = \"show\").",
            ["TargetId không hợp lệ."] = "TargetId is not valid.",
            ["TargetType không hợp lệ."] = "TargetType is not valid.",
            ["Tên dòng nhạc/cảm xúc không được để trống."] = "The mood name must not be empty.",
            ["Tên loại buổi diễn không được để trống."] = "The concert category name must not be empty.",
            ["Tên phong cách không gian không được để trống."] = "The atmosphere name must not be empty.",
            ["Tên thể loại không được để trống."] = "The genre name must not be empty.",
            ["Thiếu khoá cấu hình."] = "The configuration key is missing.",
            ["Thiếu tham số vnp_TxnRef từ VNPay."] = "The vnp_TxnRef parameter from VNPay is missing.",
            ["Thiếu token đặt lại mật khẩu."] = "The password reset token is missing.",
            ["Thông báo này không thuộc về bạn."] = "This notification does not belong to you.",
            ["Thông tin tài khoản đã được sửa sau khi gửi liên kết này — hãy dùng liên kết mới nhất trong email."] = "The account details were changed after this link was sent — please use the most recent link in your email.",
            ["Thời điểm đóng bán vé phải trước hoặc bằng thời gian bắt đầu show."] = "Ticket sales must close before or at the time the concert starts.",
            ["Thời gian bắt đầu phải ở tương lai."] = "The start time must be in the future.",
            ["Thời gian kết thúc phải sau thời gian bắt đầu."] = "The end time must be after the start time.",
            ["TierId không hợp lệ."] = "TierId is not valid.",
            ["Tin nhắn không được để trống."] = "The message must not be empty.",
            ["Tin nhắn không vượt quá 500 ký tự."] = "The message must not exceed 500 characters.",
            ["Tin nhắn này đã bị gỡ trước đó."] = "This message has already been removed.",
            ["Tính năng ghép ảnh 360° đang tạm ngưng nên chưa ghép được — lượt ghép của bạn không bị trừ. Bạn vẫn có thể tải lên ảnh 360° chụp sẵn."] = "360° stitching is temporarily unavailable, so the panorama could not be built — this attempt has not been counted against your allowance. You can still upload a ready-made 360° image.",
            ["Token không được rỗng."] = "The token must not be empty.",
            ["Token không được vượt quá 255 ký tự."] = "The token must not exceed 255 characters.",
            ["TotalCapacity phải lớn hơn 0."] = "TotalCapacity must be greater than 0.",
            ["Tối đa 10 không khí."] = "At most 10 atmospheres.",
            ["Tối đa 10 tâm trạng."] = "At most 10 moods.",
            ["Tối đa 10 thể loại nhạc."] = "At most 10 music genres.",
            ["Tối đa 20 ảnh cho mỗi lần ghép."] = "At most 20 photos per stitching attempt.",
            ["Tổng số tiền đã hoàn cho giao dịch này sẽ vượt quá số tiền đã thanh toán."] = "The total refunded for this payment would exceed the amount paid.",
            ["Từ chối hồ sơ phải nêu lý do — người nộp cần biết phải sửa gì để nộp lại."] = "Rejecting an application requires a reason — the applicant needs to know what to fix before resubmitting.",
            ["Từ chối tài khoản nhận tiền phải nêu lý do — chủ phòng trà cần biết phải sửa gì."] = "Rejecting a payout account requires a reason — the lounge owner needs to know what to fix.",
            ["Type phải là 'Navigate' hoặc 'Info'."] = "Type must be 'Navigate' or 'Info'.",
            ["URL bằng chứng thanh toán không được vượt quá 500 ký tự."] = "The payment evidence URL must not exceed 500 characters.",
            ["Url phải là một đường dẫn http/https hợp lệ."] = "The URL must be a valid http or https address.",
            ["User này đã là staff đang hoạt động của venue."] = "This user is already active staff at the venue.",
            ["UserId không tồn tại."] = "UserId does not exist.",
            ["Vé đã check-in, không thể chuyển nhượng."] = "This ticket has been checked in and cannot be transferred.",
            ["Vé đã được dùng để xem livestream, không thể chuyển nhượng."] = "This ticket has been used to watch the livestream and cannot be transferred.",
            ["Vé đang trong quá trình chuyển nhượng, không thể check-in lúc này."] = "This ticket is being transferred and cannot be checked in right now.",
            ["Vé đang trong quá trình chuyển nhượng, không thể hủy lúc này."] = "This ticket is being transferred and cannot be cancelled right now.",
            ["Vé giữ chỗ đã hết hạn. Vui lòng thực hiện lại."] = "The ticket hold has expired. Please start again.",
            ["Vé giữ chỗ này đã được dùng để mua vé rồi."] = "This hold has already been used to buy a ticket.",
            ["Vé giữ chỗ này đã được dùng để mua vé, không thể huỷ."] = "This hold has already been used to buy a ticket and cannot be cancelled.",
            ["Vé giữ chỗ này không thuộc về bạn."] = "This hold does not belong to you.",
            ["Vé không còn hợp lệ để nhận chuyển nhượng."] = "This ticket is no longer eligible to be transferred.",
            ["Vé không hợp lệ để check-in. Chỉ vé đã xác nhận mới được quét."] = "This ticket cannot be checked in. Only confirmed tickets can be scanned.",
            ["Vé này đang có một yêu cầu chuyển nhượng khác đang chờ xử lý."] = "This ticket already has another transfer request pending.",
            ["Vé này được chuyển nhượng cho bạn — chỉ người đã mua vé mới được hoàn tiền, và tiền luôn hoàn về đúng phương thức họ đã thanh toán. Hãy chuyển vé lại cho người mua ban đầu để họ yêu cầu hoàn."] = "This ticket was transferred to you — only the person who bought it can be refunded, and the money always returns by the method they paid with. Transfer the ticket back to the original buyer so they can request the refund.",
            ["Vé này không có giao dịch thanh toán hợp lệ để hoàn tiền."] = "This ticket has no valid payment to refund.",
            ["Vé này không có yêu cầu chuyển nhượng nào đang chờ xử lý."] = "This ticket has no pending transfer request.",
            ["Vé này không thuộc về bạn."] = "This ticket does not belong to you.",
            ["Vé online không cần check-in tại cửa."] = "Online tickets do not need to be checked in at the door.",
            ["Venue cần đăng ký tài khoản ngân hàng mặc định trước khi nộp duyệt event bán vé — đây là tài khoản nhận tiền bán vé sau khi show diễn ra."] = "The venue must register a default bank account before submitting a ticketed concert for approval — this is the account that receives the ticket revenue after the concert takes place.",
            ["Vui lòng cập nhật số điện thoại trong hồ sơ trước khi yêu cầu xác thực."] = "Please add a phone number to your profile before requesting verification.",
            ["Vui lòng chọn file ảnh."] = "Please choose an image file.",
            ["Vui lòng chọn file mô hình 3D."] = "Please choose a 3D model file.",
            ["Vui lòng đăng nhập để xem event của bạn."] = "Please sign in to see your concerts.",
            ["Vui lòng đăng nhập để xem phòng trà của bạn."] = "Please sign in to see your music lounge.",
            ["Vui lòng để lại số điện thoại liên hệ nếu không đăng nhập."] = "Please leave a contact phone number if you are not signed in.",
            ["Vui lòng mô tả khiếu nại."] = "Please describe your complaint.",
            ["Vui lòng nhập ngày sinh như trên CCCD/CMND."] = "Please enter the date of birth exactly as it appears on the ID card.",
            ["Vui lòng tải ảnh mặt sau CCCD/CMND."] = "Please upload the back of the ID card.",
            ["Vui lòng tải ảnh mặt trước CCCD/CMND."] = "Please upload the front of the ID card.",
            ["Vui lòng xác thực email trước khi đăng nhập."] = "Please verify your email address before signing in.",
            ["X/Y phải cùng có giá trị hoặc cùng để trống (xóa vị trí)."] = "X and Y must both have values, or both be empty (which clears the position).",
            ["X/Y/Z phải cùng có giá trị hoặc cùng để trống (xóa vị trí)."] = "X, Y and Z must all have values, or all be empty (which clears the position).",
            ["Yêu cầu hoàn tiền này chưa được duyệt."] = "This refund request has not been approved.",
            ["Yêu cầu hoàn tiền này đã được xử lý trước đó."] = "This refund request has already been processed.",
            ["Yêu cầu hoàn tiền này đã được xử lý."] = "This refund request has already been processed.",
            ["Yêu cầu hoàn tiền này không phải của bạn."] = "This refund request is not yours.",
            ["ZoneId không tồn tại."] = "ZoneId does not exist.",
        }
        .ToFrozenDictionary(StringComparer.Ordinal);
}
