// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLounge.Infrastructure.Persistence;

#nullable disable

namespace MusicLounge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624054010_AddTierTotalCapacity")]
    partial class AddTierTotalCapacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicLounge.Domain.Entities.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CollabScore")
                        .HasColumnType("real");

                    b.Property<float>("ContentScore")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<float>("CustomScore")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<float>("FinalScore")
                        .HasColumnType("real");

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoungeShowId");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.HasIndex("UserId", "LoungeShowId")
                        .IsUnique();

                    b.ToTable("AiRecommendations");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoungeId")
                        .HasColumnType("int");

                    b.Property<int?>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoungeId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("UserId", "LoungeId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDebit")
                        .HasColumnType("bit");

                    b.Property<string>("JournalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("PaymentId");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Livestream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudflareInputId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HlsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.Property<string>("RtmpUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreamKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoungeShowId")
                        .IsUnique();

                    b.ToTable("livestreams", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LivestreamChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LivestreamId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LivestreamId", "SentAt");

                    b.ToTable("livestream_chat_messages", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LivestreamTicketDetail", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StreamKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("WatchedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TicketId");

                    b.ToTable("livestream_ticket_details", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ActualStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LoungeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Quota")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ScheduledEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledStart");

                    b.HasIndex("LoungeId", "Status");

                    b.ToTable("LoungeShows");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShowAtmosphere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtmosphereId")
                        .HasColumnType("int");

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtmosphereId");

                    b.HasIndex("LoungeShowId", "AtmosphereId")
                        .IsUnique();

                    b.ToTable("LoungeShowAtmospheres");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShowGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("LoungeShowId", "GenreId")
                        .IsUnique();

                    b.ToTable("LoungeShowGenres");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShowMood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.Property<int>("MoodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoodId");

                    b.HasIndex("LoungeShowId", "MoodId")
                        .IsUnique();

                    b.ToTable("LoungeShowMoods");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShowRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoungeShowId");

                    b.HasIndex("UserId", "LoungeShowId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.MusicGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.MusicLounge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Lounges", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VnPayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("LoungeShowId", "PerformerId")
                        .IsUnique();

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.PerformerGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("PerformerId", "GenreId")
                        .IsUnique();

                    b.ToTable("PerformerGenres");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.PhysicalTicketDetail", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CheckedInByStaffId")
                        .HasColumnType("int");

                    b.Property<string>("SeatInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TicketId");

                    b.ToTable("physical_ticket_details", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("OwnerId", "Status");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.ShowWishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoungeShowId");

                    b.HasIndex("UserId", "LoungeShowId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QrCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PriceId");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasFilter("[QrCode] IS NOT NULL");

                    b.HasIndex("TierId");

                    b.HasIndex("ShowId", "Status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketHold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.HasIndex("PriceId", "ExpiresAt");

                    b.ToTable("ticket_holds", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PurchaseChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Quota")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SaleEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SaleStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TierId");

                    b.ToTable("TicketPrices");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoungeShowId");

                    b.ToTable("TicketTiers");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AiConsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserBehaviourLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoungeShowId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LoungeShowId");

                    b.HasIndex("UserId", "LoungeShowId", "Action");

                    b.ToTable("BehaviourLogs");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavouriteAtmosphere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtmosphereId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtmosphereId");

                    b.HasIndex("UserId", "AtmosphereId")
                        .IsUnique();

                    b.ToTable("UserFavouriteAtmospheres");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavouriteGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("UserId", "GenreId")
                        .IsUnique();

                    b.ToTable("UserFavouriteGenres");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavouriteMood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MoodId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoodId");

                    b.HasIndex("UserId", "MoodId")
                        .IsUnique();

                    b.ToTable("UserFavouriteMoods");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.VenueAtmosphere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Atmospheres");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.AiRecommendation", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("AiRecommendations")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany("AiRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoungeShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Follow", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicLounge", "Lounge")
                        .WithMany("Follows")
                        .HasForeignKey("LoungeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.Performer", null)
                        .WithMany("Follows")
                        .HasForeignKey("PerformerId");

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lounge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Payment", "Payment")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Livestream", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithOne("Livestream")
                        .HasForeignKey("MusicLounge.Domain.Entities.Livestream", "LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoungeShow");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LivestreamChatMessage", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Livestream", "Livestream")
                        .WithMany("ChatMessages")
                        .HasForeignKey("LivestreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Livestream");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LivestreamTicketDetail", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Ticket", "Ticket")
                        .WithOne("LivestreamDetail")
                        .HasForeignKey("MusicLounge.Domain.Entities.LivestreamTicketDetail", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShow", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicLounge", "Lounge")
                        .WithMany("LoungeShows")
                        .HasForeignKey("LoungeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lounge");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShowAtmosphere", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.VenueAtmosphere", "Atmosphere")
                        .WithMany("LoungeShowAtmospheres")
                        .HasForeignKey("AtmosphereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("Atmospheres")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atmosphere");

                    b.Navigation("LoungeShow");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShowGenre", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicGenre", "Genre")
                        .WithMany("LoungeShowGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("Genres")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("LoungeShow");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShowMood", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("Moods")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.Mood", "Mood")
                        .WithMany("LoungeShowMoods")
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoungeShow");

                    b.Navigation("Mood");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShowRating", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("Ratings")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoungeShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.MusicLounge", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("MusicLounge.Domain.ValueObjects.VenueAddress", "Address", b1 =>
                        {
                            b1.Property<int>("MusicLoungeId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_District");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Address_Latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Address_Longitude");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("Ward")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_Ward");

                            b1.HasKey("MusicLoungeId");

                            b1.HasIndex("City");

                            b1.HasIndex("City", "District");

                            b1.ToTable("Lounges");

                            b1.WithOwner()
                                .HasForeignKey("MusicLoungeId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Performance", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("Performances")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.Performer", "Performer")
                        .WithMany("Performances")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoungeShow");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.PerformerGenre", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicGenre", "Genre")
                        .WithMany("PerformerGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.Performer", "Performer")
                        .WithMany("Genres")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.PhysicalTicketDetail", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Ticket", "Ticket")
                        .WithOne("PhysicalDetail")
                        .HasForeignKey("MusicLounge.Domain.Entities.PhysicalTicketDetail", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.ShowWishlist", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("Wishlists")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoungeShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.User", "Buyer")
                        .WithMany("Tickets")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MusicLounge.Domain.Entities.Payment", "Payment")
                        .WithMany("Tickets")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MusicLounge.Domain.Entities.TicketPrice", "Price")
                        .WithMany("Tickets")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "Show")
                        .WithMany("Tickets")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.TicketTier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Payment");

                    b.Navigation("Price");

                    b.Navigation("Show");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketHold", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.TicketPrice", "Price")
                        .WithMany("Holds")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany("TicketHolds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Price");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketPrice", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.TicketTier", "Tier")
                        .WithMany("Prices")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketTier", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("TicketTiers")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoungeShow");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserBehaviourLog", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.LoungeShow", "LoungeShow")
                        .WithMany("BehaviourLogs")
                        .HasForeignKey("LoungeShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany("BehaviourLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoungeShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavouriteAtmosphere", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.VenueAtmosphere", "Atmosphere")
                        .WithMany("UserFavourites")
                        .HasForeignKey("AtmosphereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany("FavouriteAtmospheres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atmosphere");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavouriteGenre", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicGenre", "Genre")
                        .WithMany("UserFavourites")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany("FavouriteGenres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavouriteMood", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Mood", "Mood")
                        .WithMany("UserFavourites")
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MusicLounge.Domain.Entities.User", "User")
                        .WithMany("FavouriteMoods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mood");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Livestream", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeShow", b =>
                {
                    b.Navigation("AiRecommendations");

                    b.Navigation("Atmospheres");

                    b.Navigation("BehaviourLogs");

                    b.Navigation("Genres");

                    b.Navigation("Livestream");

                    b.Navigation("Moods");

                    b.Navigation("Performances");

                    b.Navigation("Ratings");

                    b.Navigation("TicketTiers");

                    b.Navigation("Tickets");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Mood", b =>
                {
                    b.Navigation("LoungeShowMoods");

                    b.Navigation("UserFavourites");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.MusicGenre", b =>
                {
                    b.Navigation("LoungeShowGenres");

                    b.Navigation("PerformerGenres");

                    b.Navigation("UserFavourites");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.MusicLounge", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("LoungeShows");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Payment", b =>
                {
                    b.Navigation("LedgerEntries");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Performer", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("Genres");

                    b.Navigation("Performances");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("LivestreamDetail");

                    b.Navigation("PhysicalDetail");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketPrice", b =>
                {
                    b.Navigation("Holds");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketTier", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.User", b =>
                {
                    b.Navigation("AiRecommendations");

                    b.Navigation("BehaviourLogs");

                    b.Navigation("FavouriteAtmospheres");

                    b.Navigation("FavouriteGenres");

                    b.Navigation("FavouriteMoods");

                    b.Navigation("Follows");

                    b.Navigation("TicketHolds");

                    b.Navigation("Tickets");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.VenueAtmosphere", b =>
                {
                    b.Navigation("LoungeShowAtmospheres");

                    b.Navigation("UserFavourites");
                });
#pragma warning restore 612, 618
        }
    }
}
