// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLounge.Infrastructure.Persistence;

#nullable disable

namespace MusicLounge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621072505_AddUserCitizenCardFields")]
    partial class AddUserCitizenCardFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicLounge.Domain.Entities.AiGeneratedPoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit")
                        .HasColumnName("is_selected");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt");

                    b.HasKey("Id")
                        .HasName("p_k_ai_generated_posters");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_ai_generated_posters_event_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("i_x_ai_generated_posters_owner_id");

                    b.ToTable("ai_generated_posters", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<decimal>("RecommendationScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("recommendation_score");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_ai_recommendations");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_ai_recommendations_event_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_ai_recommendations_user_id");

                    b.ToTable("ai_recommendations", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("LoungeId")
                        .HasColumnType("int")
                        .HasColumnName("lounge_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("photo_url");

                    b.HasKey("Id")
                        .HasName("p_k_artists");

                    b.HasIndex("LoungeId")
                        .HasDatabaseName("i_x_artists_lounge_id");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.ArtistGenre", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int")
                        .HasColumnName("artist_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.HasKey("ArtistId", "GenreId")
                        .HasName("p_k_artist_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("i_x_artist_genres_genre_id");

                    b.ToTable("artist_genres", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int")
                        .HasColumnName("artist_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<int>("DonorId")
                        .HasColumnType("int")
                        .HasColumnName("donor_id");

                    b.Property<int>("LivestreamId")
                        .HasColumnType("int")
                        .HasColumnName("livestream_id");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.HasKey("Id")
                        .HasName("p_k_donations");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("i_x_donations_artist_id");

                    b.HasIndex("DonorId")
                        .HasDatabaseName("i_x_donations_donor_id");

                    b.HasIndex("LivestreamId")
                        .HasDatabaseName("i_x_donations_livestream_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("i_x_donations_payment_id");

                    b.ToTable("donations", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CancellationAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("cancellation_allowed");

                    b.Property<int?>("CancellationDeadlineHours")
                        .HasColumnType("int")
                        .HasColumnName("cancellation_deadline_hours");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<int>("LoungeId")
                        .HasColumnType("int")
                        .HasColumnName("lounge_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("OfflineQuota")
                        .HasColumnType("int")
                        .HasColumnName("offline_quota");

                    b.Property<int>("OnlineQuota")
                        .HasColumnType("int")
                        .HasColumnName("online_quota");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("poster_url");

                    b.Property<decimal?>("RefundPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("refund_percentage");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TicketSaleClosesAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ticket_sale_closes_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_events");

                    b.HasIndex("LoungeId")
                        .HasDatabaseName("i_x_events_lounge_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventAreaTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("TotalQuota")
                        .HasColumnType("int")
                        .HasColumnName("total_quota");

                    b.HasKey("Id")
                        .HasName("p_k_event_area_tickets");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("i_x_event_area_tickets_area_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_event_area_tickets_event_id");

                    b.ToTable("event_area_tickets", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventArtist", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int")
                        .HasColumnName("artist_id");

                    b.HasKey("EventId", "ArtistId")
                        .HasName("p_k_event_artists");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("i_x_event_artists_artist_id");

                    b.ToTable("event_artists", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventAtmosphere", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("AtmosphereId")
                        .HasColumnType("int")
                        .HasColumnName("atmosphere_id");

                    b.HasKey("EventId", "AtmosphereId")
                        .HasName("p_k_event_atmospheres");

                    b.HasIndex("AtmosphereId")
                        .HasDatabaseName("i_x_event_atmospheres_atmosphere_id");

                    b.ToTable("event_atmospheres", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventGenre", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.HasKey("EventId", "GenreId")
                        .HasName("p_k_event_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("i_x_event_genres_genre_id");

                    b.ToTable("event_genres", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventModeration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDecision")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_decision");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("AiDecision")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_decision");

                    b.Property<decimal?>("AiScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("ai_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("FlagReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("flag_reason");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("risk_level");

                    b.HasKey("Id")
                        .HasName("p_k_event_moderations");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("i_x_event_moderations_admin_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_event_moderations_event_id");

                    b.ToTable("event_moderations", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventMood", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("MoodId")
                        .HasColumnType("int")
                        .HasColumnName("mood_id");

                    b.HasKey("EventId", "MoodId")
                        .HasName("p_k_event_moods");

                    b.HasIndex("MoodId")
                        .HasDatabaseName("i_x_event_moods_mood_id");

                    b.ToTable("event_moods", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit")
                        .HasColumnName("is_removed");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_text");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasColumnName("stars");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_event_ratings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_event_ratings_user_id");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_event_ratings_event_id_user_id");

                    b.ToTable("event_ratings", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventWishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("saved_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_event_wishlists");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_event_wishlists_event_id");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("i_x_event_wishlists_user_id_event_id");

                    b.ToTable("event_wishlists", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.FnbMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.Property<int>("LoungeId")
                        .HasColumnType("int")
                        .HasColumnName("lounge_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("p_k_fnb_menu_items");

                    b.HasIndex("LoungeId")
                        .HasDatabaseName("i_x_fnb_menu_items_lounge_id");

                    b.ToTable("fnb_menu_items", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.FnbOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<int>("AudienceId")
                        .HasColumnType("int")
                        .HasColumnName("audience_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<bool>("PaymentConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("payment_confirmed");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_fnb_orders");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("i_x_fnb_orders_area_id");

                    b.HasIndex("AudienceId")
                        .HasDatabaseName("i_x_fnb_orders_audience_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_fnb_orders_event_id");

                    b.ToTable("fnb_orders", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.FnbOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit")
                        .HasColumnName("cancelled");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("p_k_fnb_order_items");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("i_x_fnb_order_items_menu_item_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("i_x_fnb_order_items_order_id");

                    b.ToTable("fnb_order_items", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int")
                        .HasColumnName("artist_id");

                    b.HasKey("UserId", "ArtistId")
                        .HasName("p_k_follows");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("i_x_follows_artist_id");

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Livestream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("RecordingUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recording_url");

                    b.Property<DateTime?>("RewatchUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("rewatch_until");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stream_url");

                    b.HasKey("Id")
                        .HasName("p_k_livestreams");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("i_x_livestreams_event_id");

                    b.ToTable("livestreams", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<int>("LoungeId")
                        .HasColumnType("int")
                        .HasColumnName("lounge_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("p_k_lounge_images");

                    b.HasIndex("LoungeId")
                        .HasDatabaseName("i_x_lounge_images_lounge_id");

                    b.ToTable("lounge_images", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("LoungeId")
                        .HasColumnType("int")
                        .HasColumnName("lounge_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_lounge_staff");

                    b.HasIndex("LoungeId")
                        .HasDatabaseName("i_x_lounge_staff_lounge_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_lounge_staff_user_id");

                    b.ToTable("lounge_staff", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_moods");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_moods_name");

                    b.ToTable("moods", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.MusicGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_music_genres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_music_genres_name");

                    b.ToTable("music_genres", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.MusicLounge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("AreaLayoutImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area_layout_image_url");

                    b.Property<int?>("AtmosphereId")
                        .HasColumnType("int")
                        .HasColumnName("atmosphere_id");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bank_name");

                    b.Property<int>("CapacityTotal")
                        .HasColumnType("int")
                        .HasColumnName("capacity_total");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEscrowRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_escrow_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int>("ReputationScore")
                        .HasColumnType("int")
                        .HasColumnName("reputation_score");

                    b.HasKey("Id")
                        .HasName("p_k_music_lounges");

                    b.HasIndex("AtmosphereId")
                        .HasDatabaseName("i_x_music_lounges_atmosphere_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("i_x_music_lounges_owner_id");

                    b.ToTable("music_lounges", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.OwnerSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<string>("PaymentRef")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_ref");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_owner_subscriptions");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("i_x_owner_subscriptions_owner_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("i_x_owner_subscriptions_package_id");

                    b.ToTable("owner_subscriptions", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("destination");

                    b.Property<string>("GatewayRef")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gateway_ref");

                    b.Property<int>("PayerId")
                        .HasColumnType("int")
                        .HasColumnName("payer_id");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("subscription_id");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.HasIndex("PayerId")
                        .HasDatabaseName("i_x_payments_payer_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("i_x_payments_subscription_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("i_x_payments_ticket_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.SeatingArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("LoungeId")
                        .HasColumnType("int")
                        .HasColumnName("lounge_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_seating_areas");

                    b.HasIndex("LoungeId")
                        .HasDatabaseName("i_x_seating_areas_lounge_id");

                    b.ToTable("seating_areas", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.SubscriptionPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<bool>("HasAiPoster")
                        .HasColumnType("bit")
                        .HasColumnName("has_ai_poster");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxTicketsPerEvent")
                        .HasColumnType("int")
                        .HasColumnName("max_tickets_per_event");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("p_k_subscription_packages");

                    b.ToTable("subscription_packages", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("area_id");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checked_in_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("OnlineVerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("online_verified_at");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchased_at");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("qr_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ticket_type");

                    b.HasKey("Id")
                        .HasName("p_k_tickets");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("i_x_tickets_area_id");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("i_x_tickets_buyer_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_tickets_event_id");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_tickets_qr_code");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketHold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EventAreaTicketId")
                        .HasColumnType("int")
                        .HasColumnName("event_area_ticket_id");

                    b.Property<DateTime>("HeldUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("held_until");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<bool>("Released")
                        .HasColumnType("bit")
                        .HasColumnName("released");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_ticket_holds");

                    b.HasIndex("EventAreaTicketId")
                        .HasDatabaseName("i_x_ticket_holds_event_area_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_ticket_holds_user_id");

                    b.ToTable("ticket_holds", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auth_provider");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CitizenCardBackImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("citizen_card_back_image_url");

                    b.Property<string>("CitizenCardFrontImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("citizen_card_front_image_url");

                    b.Property<string>("CitizenCardNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("citizen_card_number");

                    b.Property<string>("CitizenCardStorageProvider")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("citizen_card_storage_provider");

                    b.Property<DateTime?>("CitizenCardUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("citizen_card_updated_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("CitizenCardNumber")
                        .HasDatabaseName("i_x_users_citizen_card_number");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserBehaviourLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_behaviour_log");

                    b.HasIndex("EventId")
                        .HasDatabaseName("i_x_user_behaviour_log_event_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_behaviour_log_user_id");

                    b.ToTable("user_behaviour_log", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavoriteAtmosphere", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("AtmosphereId")
                        .HasColumnType("int")
                        .HasColumnName("atmosphere_id");

                    b.HasKey("UserId", "AtmosphereId")
                        .HasName("p_k_user_favorite_atmospheres");

                    b.HasIndex("AtmosphereId")
                        .HasDatabaseName("i_x_user_favorite_atmospheres_atmosphere_id");

                    b.ToTable("user_favorite_atmospheres", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavoriteGenre", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.HasKey("UserId", "GenreId")
                        .HasName("p_k_user_favorite_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("i_x_user_favorite_genres_genre_id");

                    b.ToTable("user_favorite_genres", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavoriteMood", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("MoodId")
                        .HasColumnType("int")
                        .HasColumnName("mood_id");

                    b.HasKey("UserId", "MoodId")
                        .HasName("p_k_user_favorite_moods");

                    b.HasIndex("MoodId")
                        .HasDatabaseName("i_x_user_favorite_moods_mood_id");

                    b.ToTable("user_favorite_moods", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.VenueAtmosphere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_venue_atmospheres");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_venue_atmospheres_name");

                    b.ToTable("venue_atmospheres", (string)null);
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.AiGeneratedPoster", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_generated_posters_events_event_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_generated_posters_users_owner_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.AiRecommendation", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_recommendations_events_event_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_recommendations_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Artist", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicLounge", null)
                        .WithMany()
                        .HasForeignKey("LoungeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_artists_music_lounges_lounge_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.ArtistGenre", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_artist_genres_artists_artist_id");

                    b.HasOne("MusicLounge.Domain.Entities.MusicGenre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_artist_genres_music_genres_genre_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Donation", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_donations_artists_artist_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_donations_users_donor_id");

                    b.HasOne("MusicLounge.Domain.Entities.Livestream", null)
                        .WithMany()
                        .HasForeignKey("LivestreamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_donations_livestreams_livestream_id");

                    b.HasOne("MusicLounge.Domain.Entities.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_donations_payments_payment_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Event", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicLounge", null)
                        .WithMany()
                        .HasForeignKey("LoungeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_events_music_lounges_lounge_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventAreaTicket", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.SeatingArea", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_area_tickets_seating_areas_area_id");

                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_area_tickets_events_event_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventArtist", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_artists_artists_artist_id");

                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_artists_events_event_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventAtmosphere", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.VenueAtmosphere", null)
                        .WithMany()
                        .HasForeignKey("AtmosphereId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_atmospheres_venue_atmospheres_atmosphere_id");

                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_atmospheres_events_event_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventGenre", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_genres_events_event_id");

                    b.HasOne("MusicLounge.Domain.Entities.MusicGenre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_genres_music_genres_genre_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventModeration", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("f_k_event_moderations_users_admin_id");

                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_moderations_events_event_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventMood", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_moods_events_event_id");

                    b.HasOne("MusicLounge.Domain.Entities.Mood", null)
                        .WithMany()
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_moods_moods_mood_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventRating", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_ratings_events_event_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_ratings_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.EventWishlist", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_wishlists_events_event_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_event_wishlists_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.FnbMenuItem", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicLounge", null)
                        .WithMany()
                        .HasForeignKey("LoungeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_fnb_menu_items_music_lounges_lounge_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.FnbOrder", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.SeatingArea", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("f_k_fnb_orders_seating_areas_area_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AudienceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_fnb_orders_users_audience_id");

                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_fnb_orders_events_event_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.FnbOrderItem", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.FnbMenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_fnb_order_items_fnb_menu_items_menu_item_id");

                    b.HasOne("MusicLounge.Domain.Entities.FnbOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_fnb_order_items_fnb_orders_order_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Follow", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_follows_artists_artist_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_follows_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Livestream", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_livestreams_events_event_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeImage", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicLounge", null)
                        .WithMany()
                        .HasForeignKey("LoungeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_lounge_images_music_lounges_lounge_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.LoungeStaff", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicLounge", null)
                        .WithMany()
                        .HasForeignKey("LoungeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_lounge_staff_music_lounges_lounge_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_lounge_staff_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.MusicLounge", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.VenueAtmosphere", null)
                        .WithMany()
                        .HasForeignKey("AtmosphereId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("f_k_music_lounges_venue_atmospheres_atmosphere_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_music_lounges_users_owner_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.OwnerSubscription", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_owner_subscriptions_users_owner_id");

                    b.HasOne("MusicLounge.Domain.Entities.SubscriptionPackage", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_owner_subscriptions_subscription_packages_package_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_payments_users_payer_id");

                    b.HasOne("MusicLounge.Domain.Entities.OwnerSubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("f_k_payments_owner_subscriptions_subscription_id");

                    b.HasOne("MusicLounge.Domain.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("f_k_payments_tickets_ticket_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.SeatingArea", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicLounge", null)
                        .WithMany()
                        .HasForeignKey("LoungeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_seating_areas_music_lounges_lounge_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.SeatingArea", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("f_k_tickets_seating_areas_area_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_tickets_users_buyer_id");

                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_tickets_events_event_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.TicketHold", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.EventAreaTicket", null)
                        .WithMany()
                        .HasForeignKey("EventAreaTicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_ticket_holds_event_area_tickets_event_area_ticket_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_ticket_holds_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserBehaviourLog", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_user_behaviour_log_events_event_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_user_behaviour_log_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavoriteAtmosphere", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.VenueAtmosphere", null)
                        .WithMany()
                        .HasForeignKey("AtmosphereId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_user_favorite_atmospheres_venue_atmospheres_atmosphere_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_user_favorite_atmospheres_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavoriteGenre", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.MusicGenre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_user_favorite_genres_music_genres_genre_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_user_favorite_genres_users_user_id");
                });

            modelBuilder.Entity("MusicLounge.Domain.Entities.UserFavoriteMood", b =>
                {
                    b.HasOne("MusicLounge.Domain.Entities.Mood", null)
                        .WithMany()
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_user_favorite_moods_moods_mood_id");

                    b.HasOne("MusicLounge.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("f_k_user_favorite_moods_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
